# Generated by Django 5.1.2 on 2024-11-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('provisional_name', models.CharField(help_text='Provisional name or designation of the asteroid', max_length=100, primary_key=True, serialize=False)),
                ('official_name', models.CharField(blank=True, help_text='Official name of the asteroid', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not Confirmed'), ('pending', 'Pending Confirmation')], default='pending', help_text='Confirmation status of the asteroid', max_length=15)),
                ('target_description', models.TextField(blank=True, help_text='Brief description of the asteroid')),
                ('target_discovery_date', models.DateTimeField(blank=True, help_text='Date and time of discovery', null=True)),
                ('target_class', models.CharField(blank=True, choices=[('neo', 'Near-Earth Object'), ('comet', 'Comet'), ('asteroid', 'Asteroid'), ('trojan', 'Trojan'), ('undefined', 'Undefined')], default='undefined', help_text='Classification of the asteroid', max_length=50)),
                ('target_size', models.FloatField(blank=True, help_text='Size of the asteroid in kilometers', null=True)),
            ],
            options={
                'verbose_name': 'Asteroid',
                'verbose_name_plural': 'Asteroids',
                'ordering': ['status', 'official_name', 'provisional_name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(help_text='Name of the instrument, e.g., Alta U9000', max_length=100, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer of the instrument', max_length=100)),
                ('max_exposure_time', models.FloatField(blank=True, help_text='Maximum exposure time in milliseconds', null=True)),
                ('min_exposure_time', models.FloatField(blank=True, help_text='Minimum exposure time in milliseconds', null=True)),
                ('pixel_size', models.CharField(blank=True, help_text='Pixel size in microns, e.g., 12 x 12 microns', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('obs_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_obs', models.DateTimeField(help_text='Date and time of the observation')),
                ('exposure_time', models.FloatField(help_text='Exposure time in seconds')),
                ('ra', models.CharField(blank=True, help_text='Right Ascension in HH:MM:SS.s format', max_length=50, null=True)),
                ('dec', models.CharField(blank=True, help_text='Declination in DD:MM:SS.s format', max_length=50, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature during observation in Celsius', null=True)),
                ('filename', models.CharField(blank=True, help_text='File name of the observation FITS file', max_length=255, null=True)),
                ('asteroid', models.ForeignKey(help_text='Asteroid observed', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='gapc.asteroid', verbose_name='Observed Asteroid')),
                ('instrument', models.ForeignKey(blank=True, help_text='Instrument used for the observation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gapc.instrument')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-date_obs'],
                'unique_together': {('asteroid', 'date_obs')},
            },
        ),
    ]
