# Generated by Django 5.1.2 on 2024-11-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('target_name', models.CharField(help_text='Official name or designation of the asteroid', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('target_description', models.TextField(blank=True, help_text='Brief description of the asteroid')),
                ('target_discovery_date', models.DateField(blank=True, help_text='Date of discovery', null=True)),
                ('target_class', models.CharField(blank=True, help_text='Classification of the asteroid', max_length=50)),
                ('target_size', models.FloatField(blank=True, help_text='Size of the asteroid in kilometers', null=True)),
            ],
            options={
                'verbose_name': 'Asteroid',
                'verbose_name_plural': 'Asteroids',
                'ordering': ['target_name'],
            },
        ),
    ]
