# Generated by Django 5.1.2 on 2024-11-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('obs_id', models.BigAutoField(help_text='Auto-incrementing unique identifier for the observation', primary_key=True, serialize=False)),
                ('date_obs', models.DateTimeField(help_text='Date and time of the observation')),
                ('instrument_name', models.CharField(blank=True, help_text='Name of the instrument used', max_length=100)),
                ('exposure_time', models.FloatField(help_text='Exposure time in seconds')),
                ('asteroid', models.ForeignKey(help_text='Asteroid observed', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='gapc.asteroid', verbose_name='Observed Asteroid')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-date_obs'],
            },
        ),
    ]
