# Generated by Django 5.1.2 on 2024-11-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='target_class',
            field=models.CharField(blank=True, help_text='Classification of the asteroid, e.g., Near-Earth Object, Trojan', max_length=100, null=True),
        ),
    ]
