# Generated by Django 5.1.2 on 2024-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0002_alter_asteroid_target_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='is_neo',
            field=models.BooleanField(default=False, help_text='Whether the asteroid is a Near-Earth Object (NEO)'),
        ),
    ]
