# Generated by Django 5.1.2 on 2024-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0002_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='target_discovery_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of discovery', null=True),
        ),
    ]
