# Generated by Django 5.1.2 on 2024-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0003_asteroid_is_neo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='exposure_time',
            new_name='exptime',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='temperature',
            new_name='temperat',
        ),
        migrations.RemoveField(
            model_name='asteroid',
            name='target_description',
        ),
        migrations.RemoveField(
            model_name='asteroid',
            name='target_size',
        ),
        migrations.AddField(
            model_name='observation',
            name='exposure',
            field=models.FloatField(default=0, help_text='Exposure in seconds'),
            preserve_default=False,
        ),
    ]
