# Generated by Django 5.1.2 on 2024-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0003_alter_asteroid_target_discovery_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together={('asteroid', 'date_obs')},
        ),
        migrations.AddField(
            model_name='observation',
            name='instrument',
            field=models.CharField(blank=True, help_text='Instrument used for the observation', max_length=100),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='observation',
            name='instrument_name',
        ),
    ]
