# Generated by Django 5.1.2 on 2024-11-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0005_observation_dec_observation_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='dec',
            field=models.CharField(blank=True, help_text='Declination of the observation in degrees', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ra',
            field=models.CharField(blank=True, help_text='Right Ascension of the observation in degrees', max_length=50, null=True),
        ),
    ]
