# Generated by Django 5.1.2 on 2024-11-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0006_remove_observation_instrument_delete_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroid',
            name='target_discovery_date',
        ),
    ]
