# Generated by Django 5.1.2 on 2024-11-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0006_alter_observation_dec_alter_observation_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroid',
            name='target_class',
            field=models.CharField(blank=True, choices=[('neo', 'Near-Earth Object'), ('comet', 'Comet'), ('asteroid', 'Asteroid'), ('trojan', 'Trojan'), ('undefined', 'Undefined')], default='undefined', help_text='Classification of the asteroid', max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dec',
            field=models.CharField(blank=True, help_text='Declination in DD:MM:SS.s format', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ra',
            field=models.CharField(blank=True, help_text='Right Ascension in HH:MM:SS.s format', max_length=50, null=True),
        ),
    ]
