# Generated by Django 5.1.2 on 2024-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0007_alter_asteroid_target_class_alter_observation_dec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='fits_file_path',
            field=models.FilePathField(blank=True, help_text='File path to the associated FITS file', path='/Users/davidecapone/Documents/GAPC/gapc/media/fits'),
        ),
    ]
