# Generated by Django 5.1.2 on 2024-11-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0008_observation_fits_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='fits_file_path',
            new_name='filename',
        ),
    ]
