# Generated by Django 5.1.2 on 2024-11-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0009_rename_fits_file_path_observation_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='filename',
            field=models.FilePathField(blank=True, help_text='File path to the associated FITS file'),
        ),
    ]
