# Generated by Django 5.1.2 on 2024-11-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0010_alter_observation_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='filename',
            field=models.CharField(blank=True, help_text='File name of the observation FITS file', max_length=255, null=True),
        ),
    ]
