# Generated by Django 5.1.2 on 2024-11-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0011_alter_observation_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature during observation in Celsius', null=True),
        ),
    ]
