# Generated by Django 5.1.2 on 2024-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0012_observation_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(help_text='Name of the instrument, e.g., Alta U9000', max_length=100, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer of the instrument', max_length=100)),
                ('max_exposure_time', models.FloatField(help_text='Maximum exposure time in milliseconds')),
                ('min_exposure_time', models.FloatField(help_text='Minimum exposure time in milliseconds')),
                ('pixel_size', models.CharField(help_text='Pixel size in microns, e.g., 12 x 12 microns', max_length=20)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['name'],
            },
        ),
    ]
