# Generated by Django 5.1.2 on 2024-11-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0013_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='Instrument used for the observation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gapc.instrument'),
        ),
    ]
