# Generated by Django 5.1.2 on 2024-11-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0014_alter_observation_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='max_exposure_time',
            field=models.FloatField(blank=True, help_text='Maximum exposure time in milliseconds'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='min_exposure_time',
            field=models.FloatField(blank=True, help_text='Minimum exposure time in milliseconds'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='pixel_size',
            field=models.CharField(blank=True, help_text='Pixel size in microns, e.g., 12 x 12 microns', max_length=20),
        ),
    ]
