# Generated by Django 5.1.2 on 2024-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapc', '0015_alter_instrument_max_exposure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='max_exposure_time',
            field=models.FloatField(blank=True, help_text='Maximum exposure time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='min_exposure_time',
            field=models.FloatField(blank=True, help_text='Minimum exposure time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='pixel_size',
            field=models.CharField(blank=True, help_text='Pixel size in microns, e.g., 12 x 12 microns', max_length=20, null=True),
        ),
    ]
